apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: chat-ui
spec:
  to:
    kind: Service
    name: chat-ui
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect